# Generated by Django 5.0.6 on 2026-08-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(help_text='Area / Category, e.g. Beach, Mountain, Museum', max_length=120)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1 to 5')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.spot')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.visitor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
